template:
  metadata:
    labels:
      app: assignment-app

  spec:
    containers:
      - name: assignment-app
        image: IMAGE_PLACEHOLDER

        ports:
          - containerPort: 8080

        env:
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: APP_ENV

          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: password

        resources:
          requests:
            cpu: 100m
            memory: 128Mi

          limits:
            cpu: 500m
            memory: 512Mi

        livenessProbe:
          httpGet:
            path: /health
            port: 8080

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
