apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: assignment-ingress

spec:
  ingressClassName: nginx

  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: assignment-service
            port:
              number: 80
`
