name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  STACK_NAME: kubernetes-assignment

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/cloudformation.yaml \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM\
            --parameter-overrides \
              KeyPairName=k8s-assignment-key

      - name: Get Stack Outputs
        run: |

          ECR_URI=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs[?OutputKey=='ECRRepositoryUri'].OutputValue" \
            --output text)

          EC2_IP=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs[?OutputKey=='PublicIP'].OutputValue" \
            --output text)

          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t flask-k8s-app -f app/Dockerfile app

      - name: Tag Docker Image
        run: |
          docker tag flask-k8s-app:latest \
          $ECR_URI:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push $ECR_URI:${{ github.sha }}

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Wait For Kubernetes Bootstrap
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i private_key \
          ubuntu@$EC2_IP \
          "sudo cloud-init status --wait"

      - name: Copy K8s Manifests
        run: |
          scp -o StrictHostKeyChecking=no \
              -i private_key \
              -r K8s \
              ubuntu@$EC2_IP:/home/ubuntu/
              
      - name: Deploy to Kubernetes
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=30 \
            -o ServerAliveCountMax=20 \
            -i private_key \
            ubuntu@$EC2_IP << EOF

          set -eux

          export KUBECONFIG=/home/ubuntu/.kube/config

          cloud-init status

          kubectl get nodes

          ls -R /home/ubuntu/K8s

          kubectl get ns

          kubectl create namespace app \
          --dry-run=client \
          -o yaml \
          | kubectl apply -f -

          sed -i "s|IMAGE_PLACEHOLDER|$ECR_URI:${{ github.sha }}|g" \
          /home/ubuntu/K8s/deployment.yaml

          echo "Waiting for ingress controller..."

          echo "Ingress controller status"

          kubectl get pods -n ingress-nginx

          kubectl apply -f /home/ubuntu/K8s/configmap.yaml -n app

          kubectl apply -f /home/ubuntu/K8s/deployment.yaml -n app

          kubectl apply -f /home/ubuntu/K8s/service.yaml -n app

          kubectl apply -f /home/ubuntu/K8s/hpa.yaml -n app

          kubectl apply -f /home/ubuntu/K8s/ingress.yaml -n app

          kubectl rollout status deployment/assignment-app \
          -n app \
          --timeout=600s

          kubectl get all -n app

          EOF
